#!/usr/bin/env sh

# Adds the closure compiler to the environment variables.
export CLOSURE_PATH=~/packages/closure-compiler

alias dbw="NODE_OPTIONS=--max_old_space_size=4096 ng build --extract-css --configuration=dev --aot --watch"

alias dbcc="rm ~/databowl/data/cache/*.php"