#!/usr/bin/env sh

# Create a new directory and cd into it.
function mdcd() {
    mkdir -p "$1"
    cd "$1"
}

# Edit the Firefox User Chrome file, if it exists.
function ffuc() {
    if [ -z "${FIREFOX_USER_CHROME_PATH}" ]; then
        echo 'No FIREFOX_USER_CHROME environment variable set.'
        return 1
    fi

    vim "${FIREFOX_USER_CHROME_PATH}"
}