#!/usr/bin/env sh

# Returns true if the current directory is a git repo.
function is_git_repo() {
    git rev-parse --is-inside-work-tree 2>/dev/null
}

# Returns the currently checked out branch.
function git_current_branch() {
    git branch | grep \* | sed 's/\* //'
}

# Returns information about the current user and branch.
function git_info() {
    if [[ "$(is_git_repo)" == "true" ]]; then
        echo "$(git config user.email) on $(git_current_branch) "
    fi
}

# .DS_Store can do one!
function create_gitexcludes() {
    touch ~/.gitexcludes
    git config --global core.excludesfile ~/.gitexcludes
    echo .DS_Store >> ~/.gitexcludes
}

function create_git_aliases() {
    git config --global alias.pu "pull upstream"
    git config --global alias.co checkout
    git config --global alias.nah "reset --hard"
    git config --global alias.s status
    git config --global alias.a "add"
    git config --global alias.psu "push --set-upstream origin"
    git config --global alias.pop "stash pop"
    git config --global alias.fa "fetch --all"
}

# Enable git Autocomplete
[ -f /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash ] && . /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
