#!/usr/bin/env sh

# Changes git global config to use personal credentials.
function gitp() {
    git config --global user.email "me@tomm.us"
    echo "Changes will be committed as" $(git config user.email)
}

function gitd() {
    git config --global user.email "tsmith@databowl.com"
    echo "Changes will be committed as" $(git config user.email)
}
