#!/usr/bin/env sh

dotfiles_path=~/dotfiles

# General ----------------------------------------------------------------------
source $dotfiles_path/general

# Go ---------------------------------------------------------------------------
# Load in Go-specific stuff.
source $dotfiles_path/go

# Env --------------------------------------------------------------------------
# Loads in environment variables.
env_path=$dotfiles_path/env
source $dotfiles_path/env/master
