#!/usr/bin/env sh

dotfiles_path=~/dotfiles

# General ----------------------------------------------------------------------
# Loads in non-specific settings and scripts.
source $dotfiles_path/aliases
source $dotfiles_path/functions
source $dotfiles_path/path

# Git --------------------------------------------------------------------------
# Load in some git-specific aliases and functions.
source $dotfiles_path/git
source $dotfiles_path/gitprofiles

# PHP and Laravel --------------------------------------------------------------
# Load in some PHP-specific aliases and functions.
source $dotfiles_path/php
source $dotfiles_path/laravel

# Elixir and Phoenix -----------------------------------------------------------
# Load functions specific for Elixir lang and the Phoenix Framework.
source $dotfiles_path/elixir