#!/usr/bin/env bash

# Define environment variables here by creating a `{env}.env` file for each
# aspect of development. For example, an `aws.env` file for AWS. Files
# are not committed to git. If you wish to share the structure of
# the env file, create an `{env}.env.example` to store it.

for f in $(dirname "$0")/*.env; do source $f; done
