#!/usr/bin/env bash

# Define environment variables here by creating a new file for each aspect of
# development. For example, an `aws` file for Amazon Web Services. Files
# are not committed to git. If you wish to share the structure of the
# env file, create an `{env}.example` file to store env examples.

source $env_path/aws.env